// Generated by CoffeeScript 1.3.1
(function() {

  jQuery(function() {
    $("#emailEmailForm").submit(function(event) {
      var ret;
      ret = false;
      if ($(event.target).find("#emailSubject").val() === "") {
        ret = confirm("Are you sure ?\nSend without a Subject ? ");
      }
      if ($(event.target).find("#emailMessage").val() === "") {
        ret = confirm("Are you sure ?\nSend without a Message body ? ");
      }
      return ret;
    });
    return this;
  });

}).call(this);
