// Generated by CoffeeScript 1.3.1
(function() {

  jQuery(function() {
    $("#emailEmailForm").submit(function(event) {
      if ($(event.target).find("#emailSubject").val() === "") {
        if (confirm("Are you sure ?\nSend without a Subject ? ") !== true) {
          return false;
        }
      }
      if ($(event.target).find("#emailMessage").val() === "") {
        if (confirm("Are you sure ?\nSend without a Message body ? ") !== true) {
          return false;
        }
      }
      return true;
    });
    return this;
  });

}).call(this);
